jobs:
  workflow:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./ci/action

name: Action

on:
  schedule:
    - cron: "40 2/3 * * *"
